Swagger: '2.0'
tags:
  - name: File Processing API
get:
  description: None
responses:
  '200':
    description: Successful response
  '400':
    description: Bad Request
  '500':
    description: Internal Server Error
consumes:
    - multipart/form-data
parameters:
  - name: file 
    in: formData 
    description: The uploaded file data
    type: file


      
    